name: flutter_crypto_wallet
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animate_do: any
  auto_route: any
  collapsible_sidebar: any
  convex_bottom_bar: any
  dartz: any
  flutter_riverpod: any
  flutter_screenutil: ^5.8.4
  freezed_annotation: any
  http: any
  json_annotation: any
  lottie: any
  responsive_builder: any
  riverpod: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: any
  build_runner: any
  freezed: any
  json_serializable: any
  mocktail: any
  very_good_analysis: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/coins/

  